owner: triopsi
repo: statuspage
sites:
  - name: Triopsi Hosting Webseite
    url: 'https://triopsi-hosting.com'
  - name: WEB01
    url: 'https://admin.triopsi-hosting.com'
  - name: WEB02
    url: 'https://web02.triopsi-hosting.com:8443'
  - name: Kundeninterface
    url: 'https://cp.triopsi-hosting.com'
    icon: https://assets.triopsi-hosting.com/images/logo/favicon-96x96.ico
  - name: Webmail-01
    url: 'https://webmail.triopsi-hosting.com'
  # - name: CLOUD01
  #   url: 'https://cloud01.triopsi-hosting.com'
  - name: Host-01
    url: 'https://host1.phoenix.com.de:8006'
    __dangerous__insecure: true
  - name: Host-02
    url: 'https://host2.phoenix.com.de:8006'
    __dangerous__insecure: true
  - name: Host-03
    url: 'https://host3.phoenix.com.de:8006'
    __dangerous__insecure: true
  - name: Host-04
    url: 'https://host4.triopsi-hosting.com:8006'
    __dangerous__insecure: true
  - name: Host-05
    url: 'https://host5.triopsi-hosting.com:8006'
    __dangerous__insecure: true
status-website:
  theme: ocean
  favicon: https://assets.triopsi-hosting.com/images/logo/favicon-32x32.png
  cname: status.triopsi-hosting.com # Custom domain CNAME
  #baseUrl: /statuspage
  logoUrl: >-
    https://raw.githubusercontent.com/triopsi/statuspage/master/assets/triopsi-logo-light.svg
  name: Triopsi-Hosting Statusseite
  introTitle: >-
    **System-Überwachung**
  introMessage: Hier werden alle Sub Systeme von Triopsi Hosting
    überwacht.
  navbar:
    - title: Status
      href: /
    - title: Triopsi-Hosting
      href: 'https://triopsi-hosting.com'
assignees:
  - triopsi
i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme sind betriebsbereit
  incidentReport: 'Vorfall #$NUMBER report →'
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS beiträgen
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfall Details
  incidentFixed: Fixed
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentSubscribe: Abonnieren Sie für Updates
  incidentViewOnGitHub: Auf GitHub anschauen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Frühere Vorfälle
  pastIncidentsResolved: In $MINUTES Minuten mit $POSTS beiträgen gelöst
  liveStatus: Live Status
  overallUptime: 'Gesamtverfügbarkeit: $UPTIME'
  overallUptimeTitle: Gesamtverfügbarkeit
  averageResponseTime: 'Durchschnittliche Reaktionszeit: $TIMEms'
  averageResponseTimeTitle: Durchschnittliche Antwort
  sevelDayResponseTime: 7-tages Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Up
  down: Down
  degraded: Verschlechtert
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer: >-
    Diese Seite wurde automatisch erstellt. Powered by
    [Upptime](https://upptime.js.org) |
    [Impressum](https://triopsi-hosting.com/impressum/) |
    [Support](mailto:support@triopsi.com)
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: >-
    You have exceeded the number of requests you can do in an hour, so you'll
    have to wait before accessing this website again. Alternately, you can add a
    GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: >-
    This website uses the GitHub API to access real-time data about our
    websites' status. By default, GitHub allows each IP address 60 requests per
    hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: >-
    You can wait for another hour and your IP address' limit will be restored.
    Alternately, you can add your GitHub Personal Access Token, which gives you
    an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Gehen Sie zur Homepage
  pastScheduledMaintenance: Vergangene geplante Wartung
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION minuten
  scheduledMaintenanceSummaryStarts: Startet am $DATE für $DURATION minuten
  startedAt: Gestartet am
  startsAt: Startet am
  duration: Dauer
  durationMin: $DURATION minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant

